export const DEFAULT_LAYERS = [
  { key: 'bodyWash', label: 'Body Wash', shortLabel: 'Wash' },
  { key: 'bodyLotion', label: 'Body Lotion', shortLabel: 'Lotion' },
  { key: 'bodyOil', label: 'Body Oil', shortLabel: 'Oil' },
  { key: 'perfumeOil', label: 'Perfume Oil', shortLabel: 'Perfume Oil' },
  { key: 'bodyMist', label: 'Body Mist', shortLabel: 'Mist' },
  { key: 'perfumesToppers', label: 'Perfumes and Toppers', shortLabel: 'Perfume/Topper' },
];

export const DEFAULT_SCENTS = [
  { name: 'A Thousand Wishes', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Angham', layers: ['perfumesToppers'] },
  { name: 'Animal Cracker', layers: ['bodyWash'] },
  { name: 'Apple Crumble', layers: ['bodyWash'] },
  { name: 'Aquatic Lemon 152', layers: ['perfumesToppers'] },
  { name: 'Ariel', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Aurora', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Balinese Coconut', layers: ['perfumeOil'] },
  { name: 'Banana Crème Body Butter', layers: ['bodyLotion'] },
  { name: 'Banana Milkshake', layers: ['bodyMist'] },
  { name: 'Bare', layers: ['perfumesToppers', 'bodyMist'] },
  { name: 'Bare Seduction Daydream', layers: ['bodyMist'] },
  { name: 'Bare Sueded Vanilla', layers: ['perfumesToppers'] },
  { name: 'Bare Vanilla', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Belle', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Blushing Vanilla', layers: ['perfumesToppers'] },
  { name: 'Bombshell Passion', layers: ['perfumesToppers', 'bodyMist'] },
  { name: 'Bon Bon Banane', layers: ['perfumesToppers'] },
  { name: 'Bonaffi', layers: ['perfumesToppers'] },
  { name: 'Butterfly', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Cabana Girl', layers: ['bodyWash'] },
  { name: 'Cafe Caramel', layers: ['perfumesToppers'] },
  { name: 'Chai Eclair', layers: ['perfumesToppers'] },
  { name: 'Champagne Toast', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Chance Eau Splendide', layers: ['perfumesToppers'] },
  { name: 'Cherry Bon Bon Bliss', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Cherry Kiss', layers: ['perfumeOil'] },
  { name: 'Cherry Kiss EDT', layers: ['perfumesToppers'] },
  { name: 'Cherry Pop', layers: ['bodyOil'] },
  { name: 'Cherry Vanilla Wood 79', layers: ['perfumesToppers'] },
  { name: 'Chilled Ginger Tea', layers: ['bodyWash'] },
  { name: 'Cinderella', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Citron and Sage', layers: ['bodyWash'] },
  { name: 'Cloud', layers: ['perfumesToppers', 'bodyMist'] },
  { name: 'Coconut Creme', layers: ['perfumeOil'] },
  { name: 'Coconut Creme EDT', layers: ['perfumesToppers'] },
  { name: 'Coconut Crème Body Butter', layers: ['bodyLotion'] },
  { name: 'Coconut Milk', layers: ['perfumesToppers'] },
  { name: 'Coconut Waters', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Creme de Clementine', layers: ['perfumeOil', 'perfumesToppers'] },
  { name: 'Creme de Pistachio', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Dark Kiss', layers: ['bodyLotion'] },
  { name: 'Daring', layers: ['perfumesToppers'] },
  { name: 'Devotion', layers: ['perfumesToppers'] },
  { name: 'Dreaming of Rio', layers: ['bodyWash', 'bodyLotion', 'bodyMist'] },
  { name: 'Dreaming of Rio Body Butter', layers: ['bodyLotion'] },
  { name: 'Dreamist Marshmallow Skies EDT', layers: ['perfumesToppers'] },
  { name: 'Eau de Coconut', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Eden Juicy Apple', layers: ['perfumesToppers'] },
  { name: 'Evil Queen', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Fall in Bloom', layers: ['bodyLotion'] },
  { name: 'Fame', layers: ['perfumesToppers'] },
  { name: 'Floral Blush', layers: ['perfumesToppers', 'bodyMist'] },
  { name: 'Fresh Cream Soft Velvet', layers: ['perfumesToppers'] },
  { name: 'Fresh Cream Warm Cashmere', layers: ['bodyWash', 'perfumesToppers'] },
  { name: 'Fruity Musk', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Gelato Gourmand 163', layers: ['perfumesToppers'] },
  { name: 'Gingham Fresh', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Gorgeous', layers: ['perfumesToppers'] },
  { name: 'Guava Twist', layers: ['perfumesToppers'] },
  { name: 'Her Elixir', layers: ['perfumesToppers'] },
  { name: 'Honey Almond', layers: ['bodyOil'] },
  { name: 'I Want Choo', layers: ['perfumesToppers'] },
  { name: 'I Want Choo Forever', layers: ['perfumesToppers'] },
  { name: 'I Want Choo With Love', layers: ['perfumesToppers'] },
  { name: 'Iced Mint Lemonade', layers: ['bodyWash'] },
  { name: 'In the Stars', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Jasmine', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Jasmine and Cedarwood', layers: ['perfumeOil'] },
  { name: 'Jasmine Peach', layers: ['bodyLotion'] },
  { name: 'Just Peachy', layers: ['perfumeOil'] },
  { name: 'Lait de Baies', layers: ['perfumesToppers'] },
  { name: 'Lait de Coco', layers: ['perfumesToppers'] },
  { name: 'Lemon Pomegranate Cream', layers: ['bodyLotion'] },
  { name: 'Libre Flowers & Flames', layers: ['perfumesToppers'] },
  { name: 'Libre Intense', layers: ['perfumesToppers'] },
  { name: 'Life is a Fairytale', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Love', layers: ['perfumesToppers'] },
  { name: 'Maleficent', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Mandarin Mimosa', layers: ['bodyWash'] },
  { name: 'Mango & Guava', layers: ['bodyOil'] },
  { name: 'Marshmallow Blush', layers: ['perfumesToppers'] },
  { name: 'Marshmallow Gourmand 166', layers: ['perfumesToppers'] },
  { name: 'Marshmallow Skies', layers: ['perfumeOil'] },
  { name: 'Mixed Berry Tart', layers: ['bodyWash'] },
  { name: 'Moana', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Mulan', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'My Way Nectar', layers: ['perfumesToppers'] },
  { name: 'Omg Juicy Pear & Sandlewood', layers: ['perfumesToppers'] },
  { name: 'Paradox', layers: ['perfumesToppers'] },
  { name: 'Peach Nectar', layers: ['bodyOil'] },
  { name: 'Peaches', layers: ['bodyMist'] },
  { name: 'Peachcello Petillant', layers: ['perfumesToppers', 'bodyMist'] },
  { name: 'Peachy Fruits 107', layers: ['perfumesToppers'] },
  { name: 'Pear & Jasmine', layers: ['bodyOil'] },
  { name: 'Pear Potion', layers: ['perfumesToppers'] },
  { name: 'Pear Pure', layers: ['perfumesToppers'] },
  { name: 'Peppermint Stick', layers: ['bodyWash'] },
  { name: 'Perfect EDP', layers: ['perfumesToppers'] },
  { name: 'Perla Pour Femme', layers: ['perfumesToppers'] },
  { name: 'Petale Ephemere', layers: ['perfumesToppers'] },
  { name: 'Pink Champagne', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Pink Marshmallow', layers: ['perfumesToppers'] },
  { name: 'Pistachio Creme', layers: ['perfumesToppers'] },
  { name: 'Pistachio Dream', layers: ['perfumeOil'] },
  { name: 'Poppy', layers: ['bodyMist'] },
  { name: 'Praline & Pistachio', layers: ['perfumesToppers'] },
  { name: 'Pumpkin Creme', layers: ['perfumesToppers'] },
  { name: 'Punch Aux Fruits', layers: ['perfumesToppers'] },
  { name: 'Pure Seduction Daydream', layers: ['bodyLotion'] },
  { name: 'Rapunzel', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Raspberry Dream', layers: ['perfumeOil'] },
  { name: 'Raspberry Dream Body Butter', layers: ['bodyLotion'] },
  { name: 'Raspberry Sorbet', layers: ['bodyWash'] },
  { name: 'Seaside Citrus', layers: ['bodyLotion'] },
  { name: 'Sleep Lavender & Vanilla Body Butter', layers: ['bodyLotion'] },
  { name: 'Snow Angel', layers: ['bodyWash'] },
  { name: 'Snow White', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Soft Vanilla & Cashmere', layers: ['perfumesToppers'] },
  { name: 'Strawberry Floral 74', layers: ['perfumesToppers'] },
  { name: 'Strawberry Spritz', layers: ['perfumeOil'] },
  { name: 'Sun', layers: ['bodyMist'] },
  { name: 'Sweet Apple', layers: ['perfumeOil'] },
  { name: 'Sweet Berry', layers: ['bodyOil'] },
  { name: 'Sweet Nothings', layers: ['perfumesToppers'] },
  { name: 'Tahitian Coconut', layers: ['bodyOil'] },
  { name: 'Tahitian Glow', layers: ['perfumesToppers'] },
  { name: 'Tahitian Vanilla', layers: ['bodyWash'] },
  { name: 'Tease Sugar Fleur', layers: ['perfumesToppers'] },
  { name: 'Tiana', layers: ['bodyMist'] },
  { name: 'Tiana Moisturizing Cream', layers: ['bodyLotion'] },
  { name: 'Tiffany Love for Her', layers: ['perfumesToppers'] },
  { name: 'Unscented', layers: ['bodyLotion'] },
  { name: 'Unscented Bakuchiol', layers: ['bodyOil'] },
  { name: 'Vanilla 28', layers: ['perfumesToppers'] },
  { name: 'Vanilla Addiction', layers: ['perfumesToppers'] },
  { name: 'Vanilla Affair', layers: ['perfumesToppers'] },
  { name: 'Vanilla Blush', layers: ['bodyOil'] },
  { name: 'Vanilla Cake', layers: ['bodyOil'] },
  { name: 'Vanilla Cashmere', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Vanilla Extreme', layers: ['perfumesToppers'] },
  { name: 'Vanilla Idol', layers: ['perfumesToppers'] },
  { name: 'Vanilla Marshmallow', layers: ['perfumeOil'] },
  { name: 'Vanilla Melt', layers: ['perfumesToppers'] },
  { name: 'Vanilla Orchid', layers: ['perfumesToppers'] },
  { name: 'Vanilla Swirl', layers: ['bodyOil'] },
  { name: 'Vanilla Wildflower', layers: ['perfumesToppers'] },
  { name: 'Vanille', layers: ['perfumesToppers'] },
  { name: 'Vanille Banane', layers: ['perfumesToppers'] },
  { name: 'Very Sexy', layers: ['perfumesToppers'] },
  { name: 'Very Sexy Night', layers: ['perfumesToppers', 'bodyMist'] },
  { name: 'Waikiki Beach', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'Warm Musk', layers: ['bodyLotion', 'bodyMist'] },
  { name: 'White Cherry', layers: ['bodyWash'] },
  { name: 'White Floral & Lavender 33', layers: ['perfumesToppers'] },
  { name: 'White Pear', layers: ['bodyWash'] },
  { name: 'Wild Rose', layers: ['perfumesToppers'] },
  { name: 'Yara', layers: ['perfumesToppers'] },
  { name: 'Yara Elixir', layers: ['perfumesToppers'] },
  { name: 'Yum Boujee Marshmallow', layers: ['perfumesToppers'] },
];

export const DEFAULT_VIBES = [
  {
    name: 'Bakery/Comfort', color: 'var(--fam-gourmand)', title: 'The Bakery Vibe (The "Comfort" Anchor)',
    logic: 'This is the heaviest, most "grounded" category. It uses gourmand notes (vanilla, caramel, praline, dough, spice) to evoke a physical place—a warm kitchen or a bakery. These scents are "dense" because they lack crisp or airy notes.',
    weight: 'Heavy, enveloping, warm.', secretWord: 'Persistence',
    secretText: 'These scents are designed to cling to clothes and skin for hours.',
    bestFor: 'High-stress days, cozy nights in, or whenever you need an emotional "hug" from your scent.',
  },
  {
    name: 'Creamy/Skin-Silk', color: 'var(--fam-woody)', title: 'The Creamy Vibe (The "Skin-Silk" Layer)',
    logic: 'This is the most "subtle" category. It uses musk, sandalwood, and "lactonic" (milky/whipped cream) notes. It isn’t trying to smell like food, but rather like the idea of softness.',
    weight: 'Weightless, smooth, diffused.', secretWord: 'Proximity',
    secretText: 'These scents don’t shout; they whisper. They stay close to your body, making you smell "naturally" delicious.',
    bestFor: 'Intimate settings, office environments, or when you want to feel put-together without being "loud."',
  },
  {
    name: 'Crisp/Clean/Reset Button', color: 'var(--fam-aromatic)', title: 'The Crisp/Clean Vibe (The "Reset" Button)',
    logic: 'This is the most "structured" category. It relies on soap-like aldehydes, clean musk, and herbal notes. It aims for a "functional" smell—you want to smell like you just stepped out of a high-end spa, not like you’re wearing a bottle of perfume.',
    weight: 'Sharp, airy, vertical (it goes "up" instead of "out").', secretWord: 'Clarity',
    secretText: 'It removes the "fuzziness" of gourmands.',
    bestFor: 'Gym, running errands, or early morning meetings when you need to feel alert.',
  },
  {
    name: 'Effervescent/Active', color: 'var(--fam-citrus)', title: 'The Effervescent Vibe (The "Energy Spark")',
    logic: 'This is the most "vibrant" category. It uses ginger, mint, citrus, and crisp, sparkling aldehydes to create a sense of movement and "fizz." It isn’t trying to smell like food or a forest; it is designed to smell like a refreshing, high-energy tonic.',
    weight: 'Lightweight, bubbly, energetic.', secretWord: 'Radiance',
    secretText: 'Unlike heavy gourmands that "sit" on the skin, effervescent scents "bounce" off the skin. They create an invisible halo of freshness that makes you feel instantly more alert.',
    bestFor: 'High-energy errand days, shopping, summer brunch, or any time you need to "wake up" your mood and feel sharp and organized.',
  },
  {
    name: 'Fruit Orchard/Natural', color: 'var(--fam-green)', title: 'The Fruit Orchard Vibe (The "Natural" Vitality)',
    logic: 'This is "Real-Life" fruit. It’s not "candy" (which is artificial/sweet); it’s "juicy" (which is watery/natural). It uses stone fruits (peach, pear, apple, cherry) to add a dose of "bounced light" to your skin.',
    weight: 'Juicy, rounded, glowing.', secretWord: 'Juiciness',
    secretText: 'It needs to smell like the fruit was just cut.',
    bestFor: 'Day dates, brunch, or outdoor shopping where you want to appear approachable and energetic.',
  },
  {
    name: 'Spicy/Sophisticated', color: 'var(--fam-amber)', title: 'The Sophisticated/Spicy Vibe (The "Power" Play)',
    logic: 'This is the most complex category. It uses resinous amber, deep woods, and sharp spices (ginger, pepper) to create a scent that is "mysterious." It doesn’t tell a simple story; it’s an adult fragrance.',
    weight: 'Dense, slow-moving, long-lasting.', secretWord: 'Complexity',
    secretText: 'These perfumes have many layers, so they change smell throughout the day.',
    bestFor: 'Evening events, date nights, or leadership roles where you want to command the room.',
  },
  {
    name: 'Tropical/Escape', color: 'var(--fam-floral)', title: 'The Tropical Vibe (The "Escape" Mechanism)',
    logic: 'This is the only category that "transports" the wearer. It uses sun-warmed ingredients like coconut, mango, guava, and honeysuckle. It’s designed to counteract the feeling of being "stuck" in a routine.',
    weight: 'Sun-drenched, radiant, expansive.', secretWord: 'Projection',
    secretText: 'Tropical scents tend to project further because they are meant to mimic the smell of skin after a day in the sun and salt.',
    bestFor: 'Vacation, pool days, or those long Arizona afternoons when you wish you were on a beach.',
  },
];

export const DEFAULT_WISH_CATEGORIES = [
  'Travel Size', 'Full Size', 'Body Wash', 'Body Lotion', 'Body Mist', 'Body Oil', 'Perfume Oil',
];
